#!/bin/bash
if [ -z ${BUILD_WORKSPACE_DIRECTORY+x} ]; then
    echo "This script must be executed with Bazel"
    exit 1
fi

REQUIREMENTS_IN_PATH="@@REQUIREMENTS_IN_PATH@@"
OUTPUT_DIR="@@OUTPUT_DIR@@"
PYTHON_INTERPRETER_PATH="@@PYTHON_INTERPRETER_PATH@@"
GENERATE_REQUIREMENTS_FILE_NAME_BINARY="@@GENERATE_REQUIREMENTS_FILE_NAME_BINARY@@"
PIP_COMPILE_BINARY="@@PIP_COMPILE_BINARY@@"

REQUIREMENTS_TXT_NAME=$($PYTHON_INTERPRETER_PATH $GENERATE_REQUIREMENTS_FILE_NAME_BINARY)
REQUIREMENTS_TXT_PATH="$BUILD_WORKSPACE_DIRECTORY/$OUTPUT_DIR/$REQUIREMENTS_TXT_NAME.txt"

echo "Compiling $REQUIREMENTS_TXT_PATH"
$PYTHON_INTERPRETER_PATH $PIP_COMPILE_BINARY \
    --output-file $REQUIREMENTS_TXT_PATH \
    --no-header \
    --generate-hashes \
    --allow-unsafe \
    "$@" \
    $REQUIREMENTS_IN_PATH
