py_library(
    name = "piprules",
    srcs = glob(["*.py"]),
    deps = [
        "@pip_pip//:lib",
        "@pip_wheel//:lib",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
)
