py_library(
    name = "piprules",
    srcs = glob(["*.py"]),
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pip_rules__pip//:lib",
        "@pip_rules__schematics//:lib",
        "@pip_rules__setuptools//:lib",
        "@pip_rules__wheel//:lib",
    ],
)
