py_binary(
    name = "compile",
    srcs = ["compile.py"],
    deps = [
        "//thirdparty/pip/tools:pip_tools"
    ],
    visibility = ["//visibility:public"],
)

exports_files(["main_template.sh"])
